services:

  # spring backend
  # react frontend
  frontend:
    container_name: dspr-frontend
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development
    # networks:
    #   - dspr-network

  # postgresql database
  # https://hub.docker.com/_/postgres
  # postgres:
  #   container_name: dspr-db
  #   image: postgres:latest
  #   restart: always
  #   volumes:
  #     - './postgres:/var/lib/postgresql/data'
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_DB=dspr
  #     - POSTGRES_USER=dspr
  #     - POSTGRES_PASSWORD=wintermute
  #   networks:
  #     - dspr-network

  # db gui
  # https://hub.docker.com/_/adminer
  # adminer:
  #   container_name: dspr-adminer
  #   image: adminer:latest
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - ADMINER_DEFAULT_SERVER=dspr-db

networks:
  dspr-network:
